server:
  port: 8070


spring:
  application:
    name: "UserManagementApp"
  datasource:
    name: MySQL Connection
    url: jdbc:mysql://localhost:3306/usermanagementdb?createDatabaseIfNotExist=true
    username: root
    password: Acle2567
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: db/changelog/master.xml
#    enabled: false